site_name: My Notes
site_url: https://nramc.github.io/my-notes/

# Repository
repo_name: nramc/my-notes
repo_url: https://github.com/nramc/my-notes

# Copyright
copyright: Made with ❤️ by Ramachandran Nellaiyappan


theme:
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.instant.progress
    - navigation.path
    - header
    - search.suggest
    - search.share
    #- navigation.footer
    - content.code.copy
    - content.code.select
    - toc.follow

extra_css:
  - assets/stylesheets/custom.css

plugins:
  - search
  - offline
  - meta
  - tags:
      listings_sort_by: !!python/name:material.plugins.tags.item_title
      listings_tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
  - pagetree


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nramc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/codewithram
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ram_n_74
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ramachandran-nellaiyappan/
    - icon: fontawesome/solid/paper-plane
      link: mailto:ramachandrannellai@gmail.com

nav:
  - Home:
      - 'Welcome': 'index.md'
      - 'Sitemap': 'table-of-index.md'
      - 'Tags': 'tags.md'
  - Java:
      - 'Validations': 'java/validations.md'
      - 'Email Template': 'java/email-templates.md'
      - 'Development Tools':
        - 'Developer Workstation Tools': 'java/development/workstation-tools.md'
        - 'Local Development Essentials': 'java/development/local-development.md'
      - 'Java Notes': 'java/java-notes.md'
  - Testing:
      - 'IntelliJ IDE Testing Plugins': 'testings/intellij-testing-tools.md'
      - 'Automation Testing Tips': 'testings/automation-tips.md'
  - Kubernetes:
      - 'Kubernetes Logs Verification': 'kubernetes/logs-verification.md'
      - 'Useful Kubernetes Commands': 'kubernetes/useful-commands.md'
  - Improvements:
      - 'Improve Code Health': 'improvements/code-health-improvements.md'
      - 'Improve Data Quality': 'improvements/data-quality.md'
      - 'Improve Documentation': 'improvements/documentation-improvements.md'
      - 'Improve Web Application': 'improvements/web-application-improvements.md'
  - Security:
      - 'Secure Coding': 'security/secure-coding.md'
      - 'Secure Password': 'security/password-security.md'
      - 'Penetration Testing': 'security/penetration-testing.md'
  - How-To:
      - 'OpenRewrite Integration': 'how-to-articles/open-rewrite.md'
      - 'New Java Application': 'how-to-articles/new-java-application-checklist.md'
      - 'HTTP Client - IntelliJ Plugin': 'how-to-articles/http-client-intellij-plugin.md'
      - 'IntelliJ Live Templates': 'how-to-articles/intellij-live-templates.md'
  - Career:
      - 'Professional Feedback': 'career/feedback-template.md'
  - About: 'about.md'



