site_name: My Notes
site_description: "Playbook for developers with coding snippets, references, procedures and HowTo guides crafted with real time experience."
site_url: https://nramc.github.io/my-notes/

# Repository
repo_name: nramc/my-notes
repo_url: https://github.com/nramc/my-notes

# Copyright
copyright: Made with ❤️ by Ramachandran Nellaiyappan


theme:
  language: en
  name: material
  custom_dir: docs/overrides
  icon:
    logo: octicons/codescan-16
    repo: fontawesome/brands/github
  favicon: assets/logo/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    #    - navigation.sections
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.indexes
    - navigation.instant.progress
    - navigation.path
    #    - navigation.expand
    - header
    - search.suggest
    - search.share
    #- navigation.footer
    - content.code.copy
    - content.code.select
    - toc.follow

extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/card-layout.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js
  - assets/javascripts/navigation-expand.js


hooks:
  - hooks/socialmedia.py

plugins:
  - search
  - offline
  - meta
  - tags:
      listings_sort_by: !!python/name:material.plugins.tags.item_title
      listings_tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
  - pagetree
  - blog:
      post_date_format: "d MMM Y"
      blog_toc: false
      post_dir: "{blog}/articles"
      post_url_format: "/{file}"
      archive: false
      pagination: true
      pagination_per_page: 10
  - social



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: true
  social:
    - icon: fontawesome/solid/user
      link: https://nramc.github.io/my-profile/
    - icon: fontawesome/brands/github
      link: https://github.com/nramc
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/ImRamachandranN
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ramachandran-nellaiyappan/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/codewithram
  analytics:
    provider: google
    property: !GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            providing <a href="https://github.com/nramc/my-notes/issues/new?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">your feedback</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Home:
      - 'Welcome': 'index.md'
      - 'Sitemap': 'table-of-index.md'
      - 'Tags': 'tags.md'
  - Java:
      - 'Validations': 'java/validations.md'
      - 'Email Template': 'java/email-templates.md'
      - 'Development Tools':
          - 'Developer Workstation Tools': 'java/development/workstation-tools.md'
          - 'Local Development Essentials': 'java/development/local-development.md'
      - 'Java Notes': 'java/java-notes.md'
  - Testing:
      - 'IntelliJ IDE Testing Plugins': 'testings/intellij-testing-tools.md'
      - 'Automation Testing Tips': 'testings/automation-tips.md'
  - Kubernetes:
      - 'Kubernetes Logs Verification': 'kubernetes/logs-verification.md'
      - 'Useful Kubernetes Commands': 'kubernetes/useful-commands.md'
  - Improvements:
      - 'Improve Code Health': 'improvements/code-health-improvements.md'
      - 'Improve Data Quality': 'improvements/data-quality.md'
      - 'Improve Documentation': 'improvements/documentation-improvements.md'
      - 'Improve Web Application': 'improvements/web-application-improvements.md'
  - Security:
      - 'Secure Coding': 'security/secure-coding.md'
      - 'Secure Password': 'security/password-security.md'
      - 'Penetration Testing': 'security/penetration-testing.md'
  - Blogs:
      - blog/index.md
  - Career:
      - 'Professional Feedback': 'career/feedback-template.md'
  - About: 'about.md'



