site_name: My Notes
theme:
  name: material

nav:
  - Home: index.md
  - Java: java-notes.md
  - Kubernetes: kubernetes-notes.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nramc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ram_n_74

